name: Test

on:
  push:
    branches: ["develop"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.1
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
